// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nnfrbvsbziossxbtkadz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5uZnJidnNiemlvc3N4YnRrYWR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NjM1ODUsImV4cCI6MjA2OTAzOTU4NX0.ojB0QtH-UIqIsVRekN40h7y-bD9N5LVVuJTk5xHTI9w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});